-- Run once against the PhonepayService database (the "charan" schema) after deploying partial refunds.
--
-- Partial refunds allow several Refund rows per payment. The old one-refund-per-payment guarantee was a UNIQUE
-- index on transaction.refund_of_transaction_id, which Hibernate's ddl-auto=update created but will never drop -
-- until it's gone, the second partial refund of any payment fails with a duplicate-key error. The limit is now
-- enforced by PhonepeService.reserveRefund() under a row lock instead.
--
-- Safe to run more than once: it looks up the unique index by column (its name was generated by Hibernate) and
-- does nothing if it is already gone. The new plain index idx_transaction_refund_of is created by Hibernate on
-- the next start.

SET @idx := (
    SELECT INDEX_NAME
    FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'transaction'
      AND COLUMN_NAME = 'refund_of_transaction_id'
      AND NON_UNIQUE = 0
    LIMIT 1
);
SET @stmt := IF(@idx IS NULL,
    'SELECT ''No unique index on refund_of_transaction_id - nothing to drop'' AS result',
    CONCAT('ALTER TABLE `transaction` DROP INDEX `', @idx, '`'));
PREPARE drop_unique_refund_index FROM @stmt;
EXECUTE drop_unique_refund_index;
DEALLOCATE PREPARE drop_unique_refund_index;
