-- Partial refunds allow several Refund rows per payment. The old one-refund-per-payment guarantee was a UNIQUE
-- index on transaction.refund_of_transaction_id, which Hibernate's ddl-auto=update created but never drops - until
-- it is gone, the second partial refund of any payment fails with a duplicate-key error. The limit is now enforced
-- by PhonepeService.reserveRefund() under a row lock instead.
--
-- This replaces db/manual-migrations/2026-10-07-allow-partial-refunds.sql: it runs automatically, and does nothing
-- on a database that never had the unique index (a new one, or one where that script was already run). The index
-- name was generated by Hibernate, so it is looked up by column.

SET @idx := (
    SELECT INDEX_NAME
    FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'transaction'
      AND COLUMN_NAME = 'refund_of_transaction_id'
      AND NON_UNIQUE = 0
    LIMIT 1
);
SET @stmt := IF(@idx IS NULL,
    'SELECT 1',
    CONCAT('ALTER TABLE `transaction` DROP INDEX `', @idx, '`'));
PREPARE drop_unique_refund_index FROM @stmt;
EXECUTE drop_unique_refund_index;
DEALLOCATE PREPARE drop_unique_refund_index;
